### ISSUE TITLE
help a n00b brother out

### ISSUE THREAD

**Issue by Natotela** [Pup-Sik/Fractals3DPlugin#9]
for the life of me - I have no idea how to use this 
I followed the readme, but it "jumps" to the phase of Material Expression Custom, placing the code, and I have no clue how to get to that complexity as pictured on the "_custom node like in screenshot_"
![image](https://user-images.githubusercontent.com/33201750/218988791-d24e54a5-3266-411b-b828-e42c7080c0b6.png)
10x

**Comment by ipupsik** [comment]
Hi! After you copied Master Material, you have to open it, and there is custom node named "fractal" (like in screenshot in readme), you have to select it and type new fractal name there, in "code" segment, will append instruction, thanks!
